import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: 50,
        backgroundColor: "#121212",
        alignItems: 'center',
        gap: 10,
    },
    text: {
        marginTop: 50,
        color: "white",
        fontFamily: "Nova",
        fontSize: 38,
        marginHorizontal: 0,
    },
    textBold: {
        color: "white",
        fontFamily: "Nova-Bold",
        fontSize: 38,
    },
    textRegular: {
        color: "white",
        fontFamily: "Nova-Bold",
        fontSize: 22,
        marginVertical: 20,
        textAlign: "center",
    },
    textSmall: {
        color: "white",
        fontFamily: "Nova-Bold",
        fontSize: 14,
        marginVertical: 20,
        marginHorizontal: 30,
        textAlign: "center",
    },
    textError: {
        color: "#ff6b6b",
        fontFamily: "Nova",
        fontSize: 14,
        marginTop: 5,
        textAlign: "center",
    },
    leftItem: {
        position: "absolute",
        left: 50,
        top: 50,
    },
    backSign: {
        color: "white",
        fontFamily: "Nova-Bold",
        textAlign: "left",
        fontSize: 25,
    },
    button: {
        backgroundColor: "white",
        padding: 15,
        borderRadius: 50,
        marginVertical: 10,
        width: "85%",
    },
    buttonDisabled: {
        backgroundColor: "#2E2E2E",
    },
    buttonContainer: {
        position: "absolute",
        bottom: 40,
        width: "100%",
        alignItems: "center",
        backgroundColor: "#121212",
        paddingTop: 20,
    },
    textBlackBold: {
        color: "black",
        fontFamily: "Nova-Bold",
        fontSize: 22,
        marginHorizontal: 70,
        textAlign: "center",
    },
    textBlackBoldDisabled: {
        color: "#777777",
    },
    imageContainer: {
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: '#2E2E2E',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 30,
        overflow: 'hidden',
    },
    profileImage: {
        width: '100%',
        height: '100%',
    },
    uploadOptions: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 20,
        marginTop: 20,
    },
    optionButton: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 25,
        padding: 15,
        minWidth: 150,
        alignItems: 'center',
    },
    optionText: {
        color: 'white',
        fontFamily: 'Nova-Bold',
        fontSize: 16,
    },
});
